export default {
    register: "/admin/register",
    login: "/admin/login",
    logout: "/admin/logout",
    addNewMenu: "/menu/addnew-menu",
    updateQRCode: "/admin/generate-qrcode",
    getTableStatus: "table-status",
    getScreenStatus: "screens",
    getUsersList: "/admin/admin-users",
    deleteUser: "/admin/delete-user",
    addInventoryList: "add-inventory",
    getInventoryList: "get-inventory",
    getAllReports: "/admin/report/orders",
    deleteQRCode: "/admin/delete-qrcode",
    uploadMenu: "/image-upload",
    qrCode: "/admin/qrcode",
    getAllMenu: "/menu/menu",
    refreshToken: "/admin/refresh-token",
    menuCategory: "/menu/menu-category",
    getAllMenus: "/menu/get-all-menus",
    order: "/order/order",
    clientEntity:"/admin/client-entity",
    seat:"/admin/seat",
    forgotPassword: "/admin/forgot-password",
    emailResetPassword: "/admin/reset-password",
    resetTempPassword:"/admin/reset-temporary-password",
    razCreatOrder: "/order/rzp-create-order",
    razSaveOrder: "/order/rzp-save-order",
    client: "/admin/client"
}

